import uuid
from typing import List, Dict, Any

NSFDC_SCHEMES: List[Dict[str, Any]] = [
    {
        "id": "SCH_MSY",
        "code": "MSY",
        "name_en": "Mahila Samriddhi Yojana (MSY)",
        "name_hi": "महिला समृद्धि योजना (MSY)",
        "category_target": ["SC"],
        "gender_target": ["Female"],
        "max_income_rural": 300000,
        "max_income_urban": 300000,
        "max_loan_amount": 140000,
        "interest_rate_pa": 4.0,
        "max_tenure_months": 60,
        "moratorium_months": 6,
        "allowed_business_types": ["Micro Enterprise", "Handicraft", "Tailoring", "Dairy/Agri", "Retail Shop", "Beauty Parlour"],
        "nsfdc_subsidy_pct": 14.0,
        "promoter_contribution_pct": 5.0,
        "description_en": "Concessional micro-credit scheme specifically designed for Scheduled Caste women entrepreneurs for income generation.",
        "description_hi": "अनुसूचित जाति की महिला उद्यमियों के लिए आय सृजन हेतु रियायती माइक्रो-क्रेडिट योजना।",
        "required_documents": [
            {"id": "doc_aadhaar", "name_en": "Aadhaar Card", "name_hi": "आधार कार्ड", "mandatory": True},
            {"id": "doc_caste", "name_en": "SC Caste Certificate", "name_hi": "अनुसूचित जाति प्रमाणपत्र", "mandatory": True},
            {"id": "doc_income", "name_en": "Income Certificate / Self Declaration", "name_hi": "आय प्रमाण पत्र / स्व घोषणा", "mandatory": True},
            {"id": "doc_bank", "name_en": "Bank Account Details (Passbook)", "name_hi": "बैंक खाता विवरण (पासबुक)", "mandatory": True},
            {"id": "doc_business_plan", "name_en": "Simple Business Proposal / Quotation", "name_hi": "व्यापार प्रस्ताव / कोटेशन", "mandatory": False}
        ]
    },
    {
        "id": "SCH_MCS",
        "code": "MCS",
        "name_en": "Micro Credit Scheme (MCS)",
        "name_hi": "माइक्रो क्रेडिट योजना (MCS)",
        "category_target": ["SC"],
        "gender_target": ["Male", "Female", "Other"],
        "max_income_rural": 300000,
        "max_income_urban": 300000,
        "max_loan_amount": 140000,
        "interest_rate_pa": 5.0,
        "max_tenure_months": 60,
        "moratorium_months": 6,
        "allowed_business_types": ["Micro Enterprise", "Small Retail", "Artisan Work", "Services", "Transport", "Repair Shop"],
        "nsfdc_subsidy_pct": 10.0,
        "promoter_contribution_pct": 5.0,
        "description_en": "Provides financial assistance for small business units, tiny trade, and self-employment projects for SC individuals.",
        "description_hi": "अनुसूचित जाति के व्यक्तियों के लिए छोटे व्यावसायिक इकाइयों, लघु व्यापार और स्व-रोजगार के लिए वित्तीय सहायता।",
        "required_documents": [
            {"id": "doc_aadhaar", "name_en": "Aadhaar Card", "name_hi": "आधार कार्ड", "mandatory": True},
            {"id": "doc_caste", "name_en": "SC Caste Certificate", "name_hi": "अनुसूचित जाति प्रमाणपत्र", "mandatory": True},
            {"id": "doc_income", "name_en": "Income Certificate", "name_hi": "आय प्रमाण पत्र", "mandatory": True},
            {"id": "doc_bank", "name_en": "Bank Passbook", "name_hi": "बैंक पासबुक", "mandatory": True}
        ]
    },
    {
        "id": "SCH_TLS",
        "code": "TLS",
        "name_en": "Term Loan Scheme (TLS)",
        "name_hi": "टर्म लोन योजना (TLS)",
        "category_target": ["SC"],
        "gender_target": ["Male", "Female", "Other"],
        "max_income_rural": 300000,
        "max_income_urban": 300000,
        "max_loan_amount": 1500000,
        "interest_rate_pa": 6.0,
        "max_tenure_months": 120,
        "moratorium_months": 6,
        "allowed_business_types": ["Manufacturing", "Services", "Agriculture Allied", "Small Industry", "Transport Fleet", "Food Processing"],
        "nsfdc_subsidy_pct": 0.0,
        "promoter_contribution_pct": 10.0,
        "description_en": "Term loan assistance up to ₹15 Lakhs for viable income generating projects in transport, service, and manufacturing sectors.",
        "description_hi": "परिवहन, सेवा और विनिर्माण क्षेत्रों में व्यावहारिक आय अर्जक परियोजनाओं के लिए ₹15 लाख तक टर्म लोन सहायता।",
        "required_documents": [
            {"id": "doc_aadhaar", "name_en": "Aadhaar Card", "name_hi": "आधार कार्ड", "mandatory": True},
            {"id": "doc_caste", "name_en": "SC Caste Certificate", "name_hi": "अनुसूचित जाति प्रमाणपत्र", "mandatory": True},
            {"id": "doc_income", "name_en": "Income Certificate", "name_hi": "आय प्रमाण पत्र", "mandatory": True},
            {"id": "doc_project_report", "name_en": "Detailed Project Report (DPR)", "name_hi": "विस्तृत परियोजना रिपोर्ट (DPR)", "mandatory": True},
            {"id": "doc_quotations", "name_en": "Machinery/Equipment Quotations", "name_hi": "मशीनरी/उपकरण उद्धरण", "mandatory": True}
        ]
    },
    {
        "id": "SCH_MKY",
        "code": "MKY",
        "name_en": "Mahila Kisan Yojana (MKY)",
        "name_hi": "महिला किसान योजना (MKY)",
        "category_target": ["SC"],
        "gender_target": ["Female"],
        "max_income_rural": 300000,
        "max_income_urban": 300000,
        "max_loan_amount": 200000,
        "interest_rate_pa": 5.0,
        "max_tenure_months": 60,
        "moratorium_months": 6,
        "allowed_business_types": ["Dairy/Agri", "Poultry", "Organic Farming", "Horticulture", "Bee Keeping", "Agri Processing"],
        "nsfdc_subsidy_pct": 12.0,
        "promoter_contribution_pct": 5.0,
        "description_en": "Concessional credit scheme for women farmers belonging to Scheduled Castes for agriculture and allied activities.",
        "description_hi": "कृषि और संबद्ध गतिविधियों के लिए अनुसूचित जाति की महिला किसानों के लिए रियायती ऋण योजना।",
        "required_documents": [
            {"id": "doc_aadhaar", "name_en": "Aadhaar Card", "name_hi": "आधार कार्ड", "mandatory": True},
            {"id": "doc_caste", "name_en": "SC Caste Certificate", "name_hi": "अनुसूचित जाति प्रमाणपत्र", "mandatory": True},
            {"id": "doc_land_patta", "name_en": "Land Document / Lease Deed / Khasra", "name_hi": "भूमि दस्तावेज / पट्टा / खसरा", "mandatory": True},
            {"id": "doc_bank", "name_en": "Bank Account Details", "name_hi": "बैंक खाता विवरण", "mandatory": True}
        ]
    },
    {
        "id": "SCH_GBS",
        "code": "GBS",
        "name_en": "Green Business Scheme (GBS)",
        "name_hi": "ग्रीन बिजनेस योजना (GBS)",
        "category_target": ["SC"],
        "gender_target": ["Male", "Female", "Other"],
        "max_income_rural": 300000,
        "max_income_urban": 300000,
        "max_loan_amount": 3000000,
        "interest_rate_pa": 6.0,
        "max_tenure_months": 120,
        "moratorium_months": 6,
        "allowed_business_types": ["E-Rickshaw", "Solar Power Unit", "Waste Recycling", "Bio-gas Plant", "Eco-friendly Packaging"],
        "nsfdc_subsidy_pct": 0.0,
        "promoter_contribution_pct": 10.0,
        "description_en": "Financial support for eco-friendly business activities such as E-Rickshaws, Solar Energy units, and Waste Management.",
        "description_hi": "ई-रिक्शा, सौर ऊर्जा इकाइयों और अपशिष्ट प्रबंधन जैसी पर्यावरण-अनुकूल व्यावसायिक गतिविधियों के लिए वित्तीय सहायता।",
        "required_documents": [
            {"id": "doc_aadhaar", "name_en": "Aadhaar Card", "name_hi": "आधार कार्ड", "mandatory": True},
            {"id": "doc_caste", "name_en": "SC Caste Certificate", "name_hi": "अनुसूचित जाति प्रमाणपत्र", "mandatory": True},
            {"id": "doc_dpr", "name_en": "Green Project Proposal", "name_hi": "ग्रीन प्रोजेक्ट प्रस्ताव", "mandatory": True},
            {"id": "doc_quotations", "name_en": "Vendor Quotations for E-Vehicle/Solar Panel", "name_hi": "ई-वाहन/सोलर पैनल विक्रेता उद्धरण", "mandatory": True}
        ]
    }
]

SYNTHETIC_CHANNEL_PARTNERS: List[Dict[str, Any]] = [
    {
        "id": "CP_UP_SCA_01",
        "name": "UP Scheduled Castes Finance & Development Corporation (UPSCFDC)",
        "type": "State Channelizing Agency (SCA)",
        "district": "Lucknow",
        "state": "Uttar Pradesh",
        "pincode": "226001",
        "lat": 26.8467,
        "lng": 80.9462,
        "supported_scheme_ids": ["SCH_MSY", "SCH_MCS", "SCH_TLS", "SCH_MKY", "SCH_GBS"],
        "capacity_score": 92,
        "capacity_label_en": "High Capacity (Fast Track)",
        "capacity_label_hi": "उच्च क्षमता (त्वरित प्रक्रिया)",
        "npa_status": "Low Risk (2.1% NPA)",
        "contact_phone": "+91 522 2286741",
        "address": "Pragati Bhawan, Press Club Road, Lucknow, Uttar Pradesh 226001",
        "avg_turnaround_days": 14,
        "last_verified": "2026-08-15"
    },
    {
        "id": "CP_UP_PNB_02",
        "name": "Punjab National Bank - Regional Microfinance Branch",
        "type": "Public Sector Bank Partner",
        "district": "Varanasi",
        "state": "Uttar Pradesh",
        "pincode": "221002",
        "lat": 25.3176,
        "lng": 82.9739,
        "supported_scheme_ids": ["SCH_MSY", "SCH_MCS", "SCH_TLS"],
        "capacity_score": 78,
        "capacity_label_en": "Moderate Capacity",
        "capacity_label_hi": "मध्यम क्षमता",
        "npa_status": "Moderate Risk (4.3% NPA)",
        "contact_phone": "+91 542 2501234",
        "address": "Cantonment Road, Near Nadesar, Varanasi, Uttar Pradesh 221002",
        "avg_turnaround_days": 21,
        "last_verified": "2026-08-20"
    },
    {
        "id": "CP_MH_SCA_01",
        "name": "Mahatma Phule Backward Class Development Corporation (MPBCDC)",
        "type": "State Channelizing Agency (SCA)",
        "district": "Mumbai Suburbs",
        "state": "Maharashtra",
        "pincode": "400051",
        "lat": 19.0600,
        "lng": 72.8426,
        "supported_scheme_ids": ["SCH_MSY", "SCH_MCS", "SCH_TLS", "SCH_GBS"],
        "capacity_score": 88,
        "capacity_label_en": "High Capacity",
        "capacity_label_hi": "उच्च क्षमता",
        "npa_status": "Low Risk (1.8% NPA)",
        "contact_phone": "+91 22 26591234",
        "address": "Bandra Kurla Complex, Bandra East, Mumbai, Maharashtra 400051",
        "avg_turnaround_days": 12,
        "last_verified": "2026-08-28"
    },
    {
        "id": "CP_BH_SCA_01",
        "name": "Bihar State Scheduled Castes Co-operative Development Corporation",
        "type": "State Channelizing Agency (SCA)",
        "district": "Patna",
        "state": "Bihar",
        "pincode": "800001",
        "lat": 25.6126,
        "lng": 85.1588,
        "supported_scheme_ids": ["SCH_MSY", "SCH_MCS", "SCH_MKY"],
        "capacity_score": 65,
        "capacity_label_en": "High Demand (Moderate Queue)",
        "capacity_label_hi": "उच्च मांग (मध्यम कतार)",
        "npa_status": "Moderate Risk (5.1% NPA)",
        "contact_phone": "+91 612 2215678",
        "address": "Maurya Lok Complex, Dak Bungalow Road, Patna, Bihar 800001",
        "avg_turnaround_days": 28,
        "last_verified": "2026-08-10"
    },
    {
        "id": "CP_DL_SBI_01",
        "name": "State Bank of India - Special Priority Lending Hub",
        "type": "Public Sector Bank Partner",
        "district": "Central Delhi",
        "state": "Delhi",
        "pincode": "110001",
        "lat": 28.6315,
        "lng": 77.2167,
        "supported_scheme_ids": ["SCH_MSY", "SCH_MCS", "SCH_TLS", "SCH_GBS"],
        "capacity_score": 95,
        "capacity_label_en": "Express Fast Track",
        "capacity_label_hi": "एक्सप्रेस फास्ट ट्रैक",
        "npa_status": "Ultra Low Risk (0.9% NPA)",
        "contact_phone": "+91 11 23349000",
        "address": "Connaught Place, Parliament Street, New Delhi 110001",
        "avg_turnaround_days": 8,
        "last_verified": "2026-09-01"
    },
    {
        "id": "CP_MP_SCA_01",
        "name": "MP State Scheduled Castes Finance & Development Corporation",
        "type": "State Channelizing Agency (SCA)",
        "district": "Bhopal",
        "state": "Madhya Pradesh",
        "pincode": "462003",
        "lat": 23.2599,
        "lng": 77.4126,
        "supported_scheme_ids": ["SCH_MSY", "SCH_MCS", "SCH_TLS", "SCH_MKY"],
        "capacity_score": 82,
        "capacity_label_en": "High Capacity",
        "capacity_label_hi": "उच्च क्षमता",
        "npa_status": "Low Risk (2.4% NPA)",
        "contact_phone": "+91 755 2554321",
        "address": "Rajiv Gandhi Bhawan, Shyamla Hills, Bhopal, MP 462003",
        "avg_turnaround_days": 15,
        "last_verified": "2026-08-25"
    }
]

SYNTHETIC_APPLICANTS: List[Dict[str, Any]] = [
    {
        "id": "APP-2026-8801",
        "name": "Ramesh Kumar",
        "age": 34,
        "gender": "Male",
        "category": "SC",
        "annual_income": 120000,
        "locality": "Rural",
        "district": "Lucknow",
        "state": "Uttar Pradesh",
        "pincode": "226001",
        "business_type": "Micro Enterprise",
        "loan_amount_requested": 100000,
        "affordability_monthly_emi": 2500,
        "matched_scheme_id": "SCH_MCS",
        "matched_partner_id": "CP_UP_SCA_01",
        "status": "Matched",
        "created_at": "2026-09-06T10:30:00Z",
        "documents_uploaded": 3,
        "documents_total": 4,
        "stuck_alert": False
    },
    {
        "id": "APP-2026-8802",
        "name": "Sunita Devi",
        "age": 31,
        "gender": "Female",
        "category": "SC",
        "annual_income": 95000,
        "locality": "Rural",
        "district": "Patna",
        "state": "Bihar",
        "pincode": "800001",
        "business_type": "Dairy/Agri",
        "loan_amount_requested": 120000,
        "affordability_monthly_emi": 2200,
        "matched_scheme_id": "SCH_MSY",
        "matched_partner_id": "CP_BH_SCA_01",
        "status": "Pending Docs",
        "created_at": "2026-09-05T14:15:00Z",
        "documents_uploaded": 2,
        "documents_total": 4,
        "stuck_alert": True
    },
    {
        "id": "APP-2026-8803",
        "name": "Anita Rani",
        "age": 28,
        "gender": "Female",
        "category": "SC",
        "annual_income": 150000,
        "locality": "Urban",
        "district": "Central Delhi",
        "state": "Delhi",
        "pincode": "110001",
        "business_type": "Beauty Parlour",
        "loan_amount_requested": 140000,
        "affordability_monthly_emi": 3000,
        "matched_scheme_id": "SCH_MSY",
        "matched_partner_id": "CP_DL_SBI_01",
        "status": "Disbursed",
        "created_at": "2026-09-02T09:00:00Z",
        "documents_uploaded": 4,
        "documents_total": 4,
        "stuck_alert": False
    },
    {
        "id": "APP-2026-8804",
        "name": "Rajesh Sonkar",
        "age": 42,
        "gender": "Male",
        "category": "SC",
        "annual_income": 210000,
        "locality": "Urban",
        "district": "Varanasi",
        "state": "Uttar Pradesh",
        "pincode": "221002",
        "business_type": "Transport",
        "loan_amount_requested": 500000,
        "affordability_monthly_emi": 8500,
        "matched_scheme_id": "SCH_TLS",
        "matched_partner_id": "CP_UP_PNB_02",
        "status": "Under Review",
        "created_at": "2026-09-06T16:45:00Z",
        "documents_uploaded": 5,
        "documents_total": 5,
        "stuck_alert": False
    },
    {
        "id": "APP-2026-8805",
        "name": "Pooja Valmiki",
        "age": 25,
        "gender": "Female",
        "category": "SC",
        "annual_income": 80000,
        "locality": "Urban",
        "district": "Mumbai Suburbs",
        "state": "Maharashtra",
        "pincode": "400051",
        "business_type": "Tailoring",
        "loan_amount_requested": 100000,
        "affordability_monthly_emi": 2000,
        "matched_scheme_id": "SCH_MSY",
        "matched_partner_id": "CP_MH_SCA_01",
        "status": "New",
        "created_at": "2026-09-07T08:10:00Z",
        "documents_uploaded": 1,
        "documents_total": 4,
        "stuck_alert": False
    },
    {
        "id": "APP-2026-8806",
        "name": "Kavita Paswan",
        "age": 30,
        "gender": "Female",
        "category": "SC",
        "annual_income": 110000,
        "locality": "Urban",
        "district": "Bhopal",
        "state": "Madhya Pradesh",
        "pincode": "462003",
        "business_type": "E-Rickshaw",
        "loan_amount_requested": 250000,
        "affordability_monthly_emi": 4200,
        "matched_scheme_id": "SCH_GBS",
        "matched_partner_id": "CP_MP_SCA_01",
        "status": "Matched",
        "created_at": "2026-09-08T09:20:00Z",
        "documents_uploaded": 4,
        "documents_total": 4,
        "stuck_alert": False,
        "intake_transcript": "मैं कविता पासवान भोपाल से हूँ। मुझे ई-रिक्शा चलाने के लिए ₹2.5 लाख का लोन चाहिए।"
    },
    {
        "id": "APP-2026-8807",
        "name": "Vikas Gautam",
        "age": 36,
        "gender": "Male",
        "category": "SC",
        "annual_income": 180000,
        "locality": "Urban",
        "district": "Agra",
        "state": "Uttar Pradesh",
        "pincode": "282001",
        "business_type": "Micro Enterprise",
        "loan_amount_requested": 140000,
        "affordability_monthly_emi": 2900,
        "matched_scheme_id": "SCH_MCS",
        "matched_partner_id": "CP_UP_SCA_01",
        "status": "Under Review",
        "created_at": "2026-09-08T11:45:00Z",
        "documents_uploaded": 4,
        "documents_total": 4,
        "stuck_alert": False,
        "intake_transcript": "I am Vikas Gautam from Agra. I need ₹1.4 Lakh loan to buy raw materials for shoe handicraft enterprise."
    },
    {
        "id": "APP-2026-8808",
        "name": "Meena Jatav",
        "age": 33,
        "gender": "Female",
        "category": "SC",
        "annual_income": 135000,
        "locality": "Rural",
        "district": "Jaipur",
        "state": "Rajasthan",
        "pincode": "302001",
        "business_type": "Dairy/Agri",
        "loan_amount_requested": 180000,
        "affordability_monthly_emi": 3200,
        "matched_scheme_id": "SCH_MKY",
        "matched_partner_id": "CP_UP_SCA_01",
        "status": "Pending Docs",
        "created_at": "2026-09-09T07:15:00Z",
        "documents_uploaded": 2,
        "documents_total": 4,
        "stuck_alert": True,
        "intake_transcript": "मैं मीना जाटव जयपुर से हूँ। डेयरी और मुर्गी पालन के लिए ₹1,80,000 लोन की आवश्यकता है।"
    },
    {
        "id": "APP-2026-8809",
        "name": "Sanjay Kadam",
        "age": 45,
        "gender": "Male",
        "category": "SC",
        "annual_income": 240000,
        "locality": "Urban",
        "district": "Pune",
        "state": "Maharashtra",
        "pincode": "411001",
        "business_type": "Transport",
        "loan_amount_requested": 750000,
        "affordability_monthly_emi": 12500,
        "matched_scheme_id": "SCH_TLS",
        "matched_partner_id": "CP_MH_SCA_01",
        "status": "Disbursed",
        "created_at": "2026-09-04T12:00:00Z",
        "documents_uploaded": 5,
        "documents_total": 5,
        "stuck_alert": False,
        "intake_transcript": "I am Sanjay Kadam from Pune. I received ₹7.5 Lakh Term Loan for small fabrication workshop."
    },
    {
        "id": "APP-2026-8810",
        "name": "Aarti Naskar",
        "age": 27,
        "gender": "Female",
        "category": "SC",
        "annual_income": 90000,
        "locality": "Rural",
        "district": "Kolkata",
        "state": "West Bengal",
        "pincode": "700001",
        "business_type": "Micro Enterprise",
        "loan_amount_requested": 100000,
        "affordability_monthly_emi": 2100,
        "matched_scheme_id": "SCH_MSY",
        "matched_partner_id": "CP_DL_SBI_01",
        "status": "New",
        "created_at": "2026-09-09T15:30:00Z",
        "documents_uploaded": 1,
        "documents_total": 4,
        "stuck_alert": False,
        "intake_transcript": "আমি আরতি নস্কর, কলকাতা থেকে। হস্তশিল্প ও ছোট মোদী দোকানের জন্য ₹১,০০,০০০ ঋণ চাই।"
    }
]
